### ISSUE TITLE
Uploading files to Slack fails with `not_in_channel` error

### ISSUE THREAD

**Issue by ben-miller-MCC** [bb-io/Slack#1]
Uploading files to Slack seems to not be working. I can send messages just fine, but trying to upload a file to the same channel results in a `not_in_channel` error – which is obviously not correct, since sending messages works fine.
<img width="437" alt="sending a message" src="https://github.com/bb-io/Slack/assets/71875509/f43daeeb-be3a-4239-aab2-a537e06326dc">
<img width="439" alt="uploading a file to the same channel" src="https://github.com/bb-io/Slack/assets/71875509/855a58a3-03f4-4a8e-a259-0f8f64ff8365">
<img width="444" alt="uploading a file - error message" src="https://github.com/bb-io/Slack/assets/71875509/31074dc2-3e6b-4cc1-a1df-94d430f7879c">

**Comment by bZverok** [comment]
I have made several tests and here is what I can recommend. The thing is, Slack demands that bot is added to the channel in order to make him able to send files. So probably your bot was not added. We have two bots, dev and prod. It works for prod, but does not work for dev, because it is not in the channel
![image](https://github.com/bb-io/Slack/assets/137277669/707a7397-94ba-4aa2-8c4b-4cf388c0ec5b)
